services:
  mysql:
    image: mysql:8
    container_name: coffee-shop-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - coffee-shop-net

  redis:
    image: redis:7
    container_name: coffee-shop-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - coffee-shop-net

  phpmyadmin:
    image: phpmyadmin
    container_name: coffee-shop-phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1
    networks:
      - coffee-shop-net

networks:
  coffee-shop-net:
    driver: bridge

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
