export const TOURIFY_ERROR_CODES = {
  USER: {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    NAME_REQUIRED: 'NAME_REQUIRED',
    NAME_TOO_SHORT: 'NAME_TOO_SHORT',
    NAME_TOO_LONG: 'NAME_TOO_LONG',
    EMAIL_REQUIRED: 'EMAIL_REQUIRED',
    EMAIL_INVALID: 'EMAIL_INVALID',
    PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
    PASSWORD_TOO_LONG: 'PASSWORD_TOO_LONG',
    PASSWORD_TOO_WEAK: 'PASSWORD_TOO_WEAK',
    PHONE_INVALID: 'PHONE_INVALID',
    STATUS_INVALID: 'STATUS_INVALID',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    EMAIL_SAME_AS_OLD: 'EMAIL_SAME_AS_OLD',
  },
  AUTH: {
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    ACCOUNT_NOT_ACTIVE: 'ACCOUNT_NOT_ACTIVE',
    OLD_PASSWORD_INCORRECT: 'OLD_PASSWORD_INCORRECT',
    PASSWORD_INCORRECT: 'PASSWORD_INCORRECT',
  },
  UPLOAD: {
    UPLOAD_FAILED: 'UPLOAD_FAILED',
    INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  },
  COMMON: {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
  },
} as const;
