export const PERMISSIONS = {
  USER: {
    LIST: 'USER_LIST',
    CREATE: 'USER_CREATE',
    UPDATE: 'USER_UPDATE',
    DELETE: 'USER_DELETE',
  },
  TOUR: {
    LIST: 'TOUR_LIST',
    CREATE: 'TOUR_CREATE',
    UPDATE: 'TOUR_UPDATE',
    DELETE: 'TOUR_DELETE',
    UPDATE_IMAGE: 'TOUR_UPDATE_IMAGE',
  },
  CATEGORY: {
    LIST: 'CATEGORY_LIST',
    CREATE: 'CATEGORY_CREATE',
    UPDATE: 'CATEGORY_UPDATE',
    DELETE: 'CATEGORY_DELETE',
  },
  CITY: {
    LIST: 'CITY_LIST',
    CREATE: 'CITY_CREATE',
    UPDATE: 'CITY_UPDATE',
    DELETE: 'CITY_DELETE',
  },
  ORDER: {
    LIST: 'ORDER_LIST',
    VIEW_DETAIL: 'ORDER_VIEW_DETAIL',
    UPDATE_STATUS: 'ORDER_UPDATE_STATUS',
    DELETE: 'ORDER_DELETE',
  },
  ROLE: {
    LIST: 'ROLE_LIST',
    CREATE: 'ROLE_CREATE',
    UPDATE: 'ROLE_UPDATE',
    DELETE: 'ROLE_DELETE',
    ASSIGN_PERMISSION: 'ROLE_ASSIGN_PERMISSION',
  },
} as const;

export enum PermissionOperator {
  AND = 'AND',
  OR = 'OR',
}
